#!/bin/bash
die() {
    echo "$*" 1>&2
    exit 1
}
file .env-production > /dev/null || die "No .env-production file in this directory"
HOST="`grep APP_HOST= .env-production | cut -d '=' -f2`"
APP_NAME="`grep APP_NAME= .env-production | cut -d '=' -f2`"
if [ -z "$HOST" ]; then
  die "No APP_HOST variable in the .env-production";
fi
if [ -z "$APP_NAME" ]; then
  die "No APP_NAME variable in the .env-production";
fi
ssh "dokku@$HOST" config:set "$APP_NAME"  "`cat .env-production | grep -v '^ *#'`"
